name: BanTempByDarkSidesYT
main: darksidesyt\BanTemp\Main
api: [3.0.0, 4.0.0]
version: 1.0.0

author: DarkSidesyt

commands:
 tempban:
  description: "Ouvrir une interface de ban"
  permission: use.tempban
  
 tcheck:
  description: "Voir la liste des bannit"
  permission: use.tcheck
